const fs = require('node:fs');
const path = require('node:path');
process.chdir(path.resolve(__dirname, '..'));
const version = fs.readFileSync('game.js','utf8').match(/const APP_VERSION = '([^']+)'/)[1];
function walk(dir) { return fs.readdirSync(dir,{withFileTypes:true}).flatMap(entry => entry.isDirectory() ? walk(dir+'/'+entry.name) : [dir+'/'+entry.name]); }
const files = ['./','./index.html','./manifest.json','./icon.svg','./icon-192.png','./icon-512.png','./offline-assets.js', './game.js?v='+version, './styles.css?v='+version, './learning-gate.js?v='+version, './frame-clock.js?v='+version];
for (const file of walk('sprites').filter(file=>file.endsWith('.svg')).sort()) files.push('./'+file+'?v='+version);
const result = '// Generated by make build.\nvar OFFLINE_ASSETS = ' + JSON.stringify(files,null,2) + ';\n';
if (process.argv.includes('--check')) { if (fs.readFileSync('offline-assets.js','utf8') !== result) throw Error('Stale offline-assets.js'); }
else fs.writeFileSync('offline-assets.js',result);
