const fs = require('node:fs');
const path = require('node:path');
process.chdir(path.resolve(__dirname, '..'));
const version = fs.readFileSync('game.js','utf8').match(/const APP_VERSION = '([^']+)'/)[1];
const html = fs.readFileSync('index.html','utf8');
function gateUrl(file) {
  const urls = Array.from(html.matchAll(/<script\b[^>]*src="([^"]+)"[^>]*>/g), match => match[1]);
  const url = urls.find(url => url.split('?')[0] === file);
  if (!url || !url.includes('?v=')) throw Error('Missing versioned script: '+file);
  return './'+url;
}
function walk(dir) { return fs.readdirSync(dir,{withFileTypes:true}).flatMap(entry => entry.isDirectory() ? walk(dir+'/'+entry.name) : [dir+'/'+entry.name]); }
const files = ['./','./index.html','./manifest.json','./icon.svg','./icon-192.png','./icon-512.png','./offline-assets.js', './game.js?v='+version, './styles.css?v='+version, gateUrl('learning-gate.js'), './frame-clock.js?v='+version];
files.push(gateUrl('learning-profile.js'), gateUrl('reading-words.js'), './READING_ASSETS.md', './READING_WORDS.md', './reading-images/manifest.json');
for (const file of walk('reading-images').filter(file=>file.endsWith('.png')).sort()) files.push('./'+file);
for (const file of walk('sprites').filter(file=>file.endsWith('.svg')).sort()) files.push('./'+file+'?v='+version);
const result = '// Generated by make build.\nvar OFFLINE_ASSETS = ' + JSON.stringify(files,null,2) + ';\n';
if (process.argv.includes('--check')) { if (fs.readFileSync('offline-assets.js','utf8') !== result) throw Error('Stale offline-assets.js'); }
else fs.writeFileSync('offline-assets.js',result);
